package drawing;

import java.awt.Dimension;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pframe1.java
 *
 * Created on Feb 27, 2010, 12:50:59 PM
 */

/**
 *
 * @author rebecca
 */
public class Pframe1 extends javax.swing.JFrame {
    Drawing d = new Drawing();

    /** Creates new form Pframe1 */
    public Pframe1() {
        initComponents();
      //  add(d);
       // jPanel1.add(d);
        add(d);
       // jPanel1.setPreferredSize(new Dimension(600,400));
                d.init();
        //        jPanel1.repaint();
        //        jPanel1.revalidate();
        //jPanel1.revalidate();
       // jScrollPane1.add(d);
       // d.setPreferredSize(400,400);
      //  d.setPreferredSize(new Dimension(400,400));
     //   JPanel p;

      //  jScrollPane1.repaint();

      //  jPanel1.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pframe1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
